trigger: none

pool:
  vmImage: windows-latest

variables:
  solutionPath: '**/*.sln'
  buildPlatform: Any CPU
  buildConfiguration: Release

stages:
  - stage: BuildCli
    displayName: Build CLI
    jobs:
      - job: build
        steps:
          - task: NuGetToolInstaller@1
            displayName: Install NuGet

          - task: NuGetCommand@2
            displayName: Run NuGet restore
            inputs:
              command: restore
              restoreSolution: $(solutionPath)
              feedsToUse: select
              vstsFeed: fbaf94f7-2d40-410a-8a27-de142d8d2313/2d8c792e-c1ad-4a66-924d-5bc4fec5fca0

          - task: VSBuild@1
            displayName: Build solution
            inputs:
              solution: $(solutionPath)
              platform: $(buildPlatform)
              configuration: $(buildConfiguration)

          - task: UseDotNet@2
            displayName: Install .NET SDK
            inputs:
              packageType: 'sdk'
              version: '8.0.408'  # Stable LTS

          - task: PowerShell@2
            displayName: List all files in working directory
            inputs:
              targetType: inline
              script: |
                Write-Host "Current directory: $(Build.SourcesDirectory)"
                Get-ChildItem -Path "$(Build.SourcesDirectory)" -Recurse -Force | ForEach-Object {
                  Write-Host $_.FullName
                }

          - task: PowerShell@2
            displayName: Check code formatting with dotnet-format
            inputs:
              targetType: inline
              script: |
                cd "$(Build.SourcesDirectory)"
                dotnet format blaise.cli/blaise.cli.sln --verify-no-changes --no-restore --verbosity diagnostic
                if ($LASTEXITCODE -eq 0) {
                  Write-Host "✅ Code formatting is clean."
                } elseif ($LASTEXITCODE -eq 2) {
                  Write-Host "⚠️ Formatting or naming violations detected (warnings)."
                  exit 0  # Optional: don't fail build for warnings
                } else {
                  Write-Host "❌ Formatting check failed due to errors."
                  exit 1
                }

          - task: VSTest@2
            displayName: Run unit tests
            inputs:
              testSelector: testAssemblies
              testAssemblyVer2: |
                **\*test*.dll
                !**\*Behaviour.dll
                !**\*TestAdapter.dll
                !**\obj\**
              searchFolder: $(System.DefaultWorkingDirectory)

          - task: CopyFiles@2
            displayName: Copy artifact
            inputs:
              SourceFolder: $(System.DefaultWorkingDirectory)
              Contents: '**\bin\$(BuildConfiguration)\**'
              TargetFolder: $(build.artifactstagingdirectory)
              CleanTargetFolder: true
              OverWrite: true

          - task: PublishBuildArtifacts@1
            displayName: Publish artifact
            inputs:
              PathtoPublish: $(Build.ArtifactStagingDirectory)
              ArtifactName: _BlaiseCli
              publishLocation: Container
