---
trigger: none

pool:
  vmImage: windows-latest

variables:
  solutionPath: '**/*.sln'
  buildPlatform: AnyCPU
  buildConfiguration: Release

stages:
  - stage: BuildCli
    displayName: Build CLI
    jobs:
      - job: build
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: sdk
              version: 8.x

          - task: DotNetCoreCLI@2
            displayName: Run dotnet restore
            inputs:
              command: restore
              projects: $(solutionPath)
              feedsToUse: select
              vstsFeed: fbaf94f7-2d40-410a-8a27-de142d8d2313/2d8c792e-c1ad-4a66-924d-5bc4fec5fca0

          - task: PowerShell@2
            displayName: Check code formatting
            inputs:
              targetType: inline
              errorActionPreference: continue
              script: |
                cd $(Build.SourcesDirectory)
                dotnet format Blaise.Cli.sln --verify-no-changes --no-restore --verbosity diagnostic
                if ($LASTEXITCODE -eq 0) {
                  Write-Host '✅ Check code formatting found no issues.'
                } elseif ($LASTEXITCODE -eq 2) {
                  Write-Host '⚠️ Check code formatting found warnings.'
                  exit 0
                } else {
                  Write-Host '❌ Check code formatting failed.'
                  exit 1
                }

          - task: DotNetCoreCLI@2
            displayName: Build solution
            inputs:
              command: build
              projects: $(solutionPath)
              arguments: --configuration $(buildConfiguration) --no-restore

          - task: DotNetCoreCLI@2
            displayName: Run unit tests
            inputs:
              command: test
              projects: '**/*[Tt]est*.csproj'
              arguments: --configuration $(buildConfiguration) --no-build

          - task: DotNetCoreCLI@2
            displayName: Run dotnet publish
            inputs:
              command: publish
              publishWebProjects: false
              projects: '**/Blaise.Cli.csproj'
              arguments: --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-restore
              zipAfterPublish: false
              modifyOutputPath: false

          - task: PublishBuildArtifacts@1
            displayName: Publish artifact
            inputs:
              PathtoPublish: $(Build.ArtifactStagingDirectory)
              ArtifactName: _BlaiseCli
              publishLocation: Container
